name: dht
description: DHT22 humidity and temperature sensor library
version: 0.0.5
homepage: https://github.com/yolkhovyy/dht_dart
author: Yuriy Olkhovyy <yuriy.olkhovyy@gmail.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  test: ^0.12.0
